// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJNQi7EaDSbW0bSOdyQTA6GNP4CyHrkrs',
    appId: '1:1081331983379:web:13ad03a43f5ff2a9890be6',
    messagingSenderId: '1081331983379',
    projectId: 'oxygenar',
    authDomain: 'oxygenar.firebaseapp.com',
    databaseURL: 'https://oxygenar-default-rtdb.firebaseio.com',
    storageBucket: 'oxygenar.appspot.com',
    measurementId: 'G-3VX7Y98F93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVQbauTcNfnZE2XoYPoPGFaCJXqXyeiCw',
    appId: '1:1081331983379:android:553f29a4f06c0854890be6',
    messagingSenderId: '1081331983379',
    projectId: 'oxygenar',
    databaseURL: 'https://oxygenar-default-rtdb.firebaseio.com',
    storageBucket: 'oxygenar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXGKqygMIZB3F-a1L_e0-Q1NGNoxqx340',
    appId: '1:1081331983379:ios:522a627a9eccbc14890be6',
    messagingSenderId: '1081331983379',
    projectId: 'oxygenar',
    databaseURL: 'https://oxygenar-default-rtdb.firebaseio.com',
    storageBucket: 'oxygenar.appspot.com',
    iosClientId: '1081331983379-c865ihm0smu30o72laoth5shoohglf9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.oxygenarFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXGKqygMIZB3F-a1L_e0-Q1NGNoxqx340',
    appId: '1:1081331983379:ios:bfe472243cbc6c23890be6',
    messagingSenderId: '1081331983379',
    projectId: 'oxygenar',
    databaseURL: 'https://oxygenar-default-rtdb.firebaseio.com',
    storageBucket: 'oxygenar.appspot.com',
    iosClientId: '1081331983379-1phdhj6g5naq04o2i06osmdr3ic8q927.apps.googleusercontent.com',
    iosBundleId: 'com.example.oxygenarFront.RunnerTests',
  );
}
